plugins {
    id "architectury-plugin" version "3.4.+"
    id "dev.architectury.loom" version "1.7.+" apply false
}

architectury {
    minecraft = minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"

    loom {
        silentMojangMappingsLicense()
    }

    repositories {
        maven { url = "https://maven.tterrag.com/" }
        maven { url = "https://mvn.devos.one/snapshots/" }
        maven { url = "https://api.modrinth.com/maven" } 
        maven { url = "https://jitpack.io" }
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
        mavenCentral()
    }

    dependencies {
        minecraft "com.mojang:minecraft:$minecraft_version"
        mappings loom.officialMojangMappings()
    }

    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.jozufozu.flywheel') {
                details.useVersion '0.6.10-7'
            }
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base.archivesName = archives_base_name
    group = maven_group

    version = "$mod_version+$project.name-$minecraft_version" + (System.getenv("GITHUB_RUN_NUMBER") != null ? "-build.${System.getenv("GITHUB_RUN_NUMBER")}" : "")

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }

    java {
        withSourcesJar()
    }
}
